version: '3'

services:
  db:
    container_name: postgres_db
    image: postgres:13-alpine

  django:
    container_name: doover_django
    build: ./
    command: bash -c "sleep 5s && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/src:rw
    ports:
      - 8000:8000
    depends_on:
      - db
